# Generated by Django 4.2.4 on 2023-10-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrequest',
            name='guid',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
    ]
