# Generated by Django 4.2.7 on 2023-11-10 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_simulationrequest_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealizationsStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.simulationrequest')),
            ],
            options={
                'db_table': 'realization_statuses',
            },
        ),
    ]
