# Generated by Django 4.2.7 on 2023-11-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_realizationsstatuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizationsstatuses',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
