# Generated by Django 4.2.7 on 2023-11-10 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_realizationsstatuses_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealizationsStatuses',
        ),
    ]
