# Generated by Django 4.2.7 on 2023-11-10 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_realizationsstatuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrequest',
            name='guid',
            field=models.CharField(default='DEFAULT', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='RealizationsStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('guid', models.ForeignKey(db_column='guid', on_delete=django.db.models.deletion.CASCADE, to='api.simulationrequest', to_field='guid')),
            ],
            options={
                'db_table': 'realization_statuses',
            },
        ),
        migrations.AddConstraint(
            model_name='realizationsstatuses',
            constraint=models.UniqueConstraint(fields=('guid', 'rid'), name='unique_guid_rid'),
        ),
    ]
